export default {
  title: "Dpowcoin Core",
  domain: "dpowcore.org",
  url: "https://dpowcore.org",
  description: "Dpowcoin Core — a cryptocurrency with Argon2id proof-of-work algorithm",
  github: "https://github.com/dpowcore-project/dpowcoin",
  github_org: "https://github.com/dpowcore-project",
  github_api_repo: "dpowcore-project/dpowcoin",
  github_license: "https://github.com/dpowcore-project/dpowcoin/blob/master/COPYING",
  github_issues: "https://github.com/dpowcore-project/dpowcoin/issues",
  github_pulls: "https://github.com/dpowcore-project/dpowcoin/pulls",
  github_contributing: "https://github.com/dpowcore-project/dpowcoin/blob/master/CONTRIBUTING.md",
  github_contributors: "https://github.com/dpowcore-project/dpowcoin/graphs/contributors",
  website_issues: "https://github.com/dpowcore-project/dpowcore.org/issues",
  guix_sigs: "https://github.com/dpowcore-project/guix.sigs",
  builder_keys: "https://github.com/dpowcore-project/guix.sigs/tree/main/builder-keys",
  gpg_fingerprint: "23B3D882F805A5D1F0A12A2535A7538B1C816E49",
  gpg_fingerprint_display: "23B3 D882 F805 A5D1 F0A1 2A25 35A7 538B 1C81 6E49",
  gpg_key_url: "https://keys.openpgp.org/search?q=23B3D882F805A5D1F0A12A2535A7538B1C816E49",
  openpgp_search: "https://keys.openpgp.org/",
  algorithm: "Argon2id",
  locales: ["en", "ru", "uk", "zh", "de", "ja", "ko", "es", "it", "pl", "tr", "pt", "fr", "ro"],
  defaultLocale: "en",
};
